-- ============================================================
-- Tipos de usuario (baseado no exemplo do PDF)
-- ============================================================
INSERT INTO TIPO_USUARIO (ID_TIPOUSUARIO, ORIGEM, DESCR) VALUES (1, 'M', 'Magistrado');
INSERT INTO TIPO_USUARIO (ID_TIPOUSUARIO, ORIGEM, DESCR) VALUES (2, 'F', 'Funcionario');
INSERT INTO TIPO_USUARIO (ID_TIPOUSUARIO, ORIGEM, DESCR) VALUES (3, 'T', 'Terceirizado');
INSERT INTO TIPO_USUARIO (ID_TIPOUSUARIO, ORIGEM, DESCR) VALUES (4, 'A', 'Aposentado');
INSERT INTO TIPO_USUARIO (ID_TIPOUSUARIO, ORIGEM, DESCR) VALUES (5, 'P', 'Pensionista');
INSERT INTO TIPO_USUARIO (ID_TIPOUSUARIO, ORIGEM, DESCR) VALUES (6, 'C', 'Cotista');
INSERT INTO TIPO_USUARIO (ID_TIPOUSUARIO, ORIGEM, DESCR) VALUES (7, 'E', 'Externo');

-- ============================================================
-- Usuarios de exemplo (baseado no exemplo do PDF)
-- ============================================================
INSERT INTO USUARIO (ID_USU, NOME_USU, MATR_USU, DATA_NASC, EMAIL, ORIGEM)
VALUES (18241, 'VIVIANE GOES DELZI', 'RJ162042', TO_DATE('13/01/2025','DD/MM/YYYY'), 'testenegocio@hotmail.com', 'E');

INSERT INTO USUARIO (ID_USU, NOME_USU, MATR_USU, DATA_NASC, EMAIL, ORIGEM)
VALUES (20101, 'SABINE SYLVIA SCHMITT', 'RJ179264', TO_DATE('13/01/2025','DD/MM/YYYY'), 'teste@teste.com.br', 'E');

INSERT INTO USUARIO (ID_USU, NOME_USU, MATR_USU, DATA_NASC, EMAIL, ORIGEM)
VALUES (29241, 'ALEXANDRE MARQUES PAULA', '30435', TO_DATE('01/02/2025','DD/MM/YYYY'), 'teste@tjrj.jus.br', 'F');

INSERT INTO USUARIO (ID_USU, NOME_USU, MATR_USU, DATA_NASC, EMAIL, ORIGEM)
VALUES (45861, 'FERNANDO LUIZ DE ABREU NETTO', '6716', TO_DATE('03/02/2025','DD/MM/YYYY'), 'teste@tjrj.jus', 'A');

INSERT INTO USUARIO (ID_USU, NOME_USU, MATR_USU, DATA_NASC, EMAIL, ORIGEM)
VALUES (21081, 'CLAUDIA MARIA MENEZES SOARES', '8041', TO_DATE('13/01/2025','DD/MM/YYYY'), 'testes@testando2.com.br', 'A');

INSERT INTO USUARIO (ID_USU, NOME_USU, MATR_USU, DATA_NASC, EMAIL, ORIGEM)
VALUES (19481, 'PAULO DA SILVA XAVIER', 'RJ144977', TO_DATE('14/09/2014','DD/MM/YYYY'), 'paulodasilvaxavierteste@uol.com.br', 'E');

INSERT INTO USUARIO (ID_USU, NOME_USU, MATR_USU, DATA_NASC, EMAIL, ORIGEM)
VALUES (35901, 'PAULA CRISTINA VASCONCELOS CAVALCANTE', 'RJ176594', TO_DATE('17/11/2019','DD/MM/YYYY'), 'adv.paulacavalcante_teste@yahoo.com.br', 'E');

INSERT INTO USUARIO (ID_USU, NOME_USU, MATR_USU, DATA_NASC, EMAIL, ORIGEM)
VALUES (22422, 'JOSE PIMENTEL JUNIOR', '24798649791', TO_DATE('13/01/2025','DD/MM/YYYY'), 'teste@teste.com.br', 'P');

INSERT INTO USUARIO (ID_USU, NOME_USU, MATR_USU, DATA_NASC, EMAIL, ORIGEM)
VALUES (43661, 'TESTE - PREPOSTO FEBRABAN', '000123', TO_DATE('02/06/2016','DD/MM/YYYY'), 'teste@teste.com.br', 'E');

-- Garante que os proximos IDs gerados pela sequence nao colidam com os exemplos acima
ALTER SEQUENCE SEQ_USUARIO INCREMENT BY 50000;
SELECT SEQ_USUARIO.NEXTVAL FROM DUAL;
ALTER SEQUENCE SEQ_USUARIO INCREMENT BY 1;

COMMIT;
